spec:
  template:
    spec:
      containers:
        - name: vertx
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: JAVA_OPTIONS
              value: '-Dvertx.cacheDirBase=/tmp -Dvertx.jgroups.config=default-configs/default-jgroups-kubernetes.xml -Djava.net.preferIPv4Stack=true'
            - name: JAVA_ARGS
              value: '-cluster'
#            - name: DB_USERNAME
#              valueFrom:
#                 secretKeyRef:
#                   name: audit-database-config
#                   key: user
#            - name: DB_PASSWORD
#              valueFrom:
#                 secretKeyRef:
#                   name: audit-database-config
#                   key: password
#            - name: DB_URL
#              valueFrom:
#                secretKeyRef:
#                  name: audit-database-config
#                  key: url
